### ISSUE TITLE
Handle plist in arguments to get

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#124]
A plist is an alternating list of keywords and values, e.g. `(:code "FOO" :rendered "BAR")`. This translates to a Python dictionary `{'code': 'FOO', 'rendered': 'BAR'}`.

WikiBase is mishandling a `get` call where the attribute is specified as a plist with both :code and :rendered attribute names.

```
(get "wikipedia-sea" "Black Sea" (:code "LENGTH" :rendered "Max. length"))
((:error TypeError :message "lispify() got multiple values for keyword argument 'typecode'"))
```

These three formats are valid:

```
(get "wikipedia-sea" "Black Sea" (:code "LENGTH"))                            ;; works
(get "wikipedia-sea" "Black Sea" "LENGTH")                                    ;; works
(get "wikipedia-sea" "Black Sea" (:code "LENGTH" :rendered "Max. length"))    ;; breaks
```

The third argument to get can either be a string or a plist of values.

`wikipediabase/provider.py` is in charge of parsing the lisp method call into a Python method call. After updating, the `get` method in wikipediabase/knowledgebase.py will need to be updated,

**Comment by fakedrake** [comment]
Actually the way I understand it the problem is both in [wikipediabase/frontend.py](https://github.com/infolab-csail/WikipediaBase/blob/master/wikipediabase/frontend.py#L39) which misinterprets plist as a function call, and in the fact that resolvers can either ask for *encoded attribute by name* or *rendered attrubute by name*, but not for *the intersection of attributes encoded as x and attributes rendered as y*.

You mark this as `ready`, I would be very interested in your approach to solving this.

**Comment by alvaromorales** [comment]
Thanks for the pointers! This issue will be investigated and worked on by one of our new students.

waffle.io adds the `ready` tag to issues, which I interpret as "ready to be worked on" instead of "finished / completed".

**Comment by fakedrake** [comment]
oh ok.
