### ISSUE TITLE
sort-symbols cake test fails locally but not on travis

### ISSUE THREAD

**Issue by chsamlee** [infolab-csail/WikipediaBase#153]
Location of test: test_sort_symbols, line 29

**Comment by alvaromorales** [comment]
The Wikipedia article "Cake" was [edited](https://en.wikipedia.org/w/index.php?title=Cake&action=history) in January. We're running the December 2015 Wikipedia dump locally.

The test succeeds on Travis because we fetch directly from wikipedia.org instead of from the database.

This test will succeed locally when we update the backend.
