### ISSUE TITLE
Plato should be a wikibase-person

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#174]
In revision 1.0.0 on navassa (currently the START production host):
```
$ telnet navassa 8023
(get-classes "Plato")
("wikibase-term" "wikibase-sections" "wikipedia-philosopher" "wikibase-person")
```
In revision 1.1.0 running experimentally on kiribati:
```
$ telnet kiribati 8023
(get-classes "Plato")
("wikibase-term" "wikibase-sections" "wikipedia-philosopher")
```

Why did Plato lose his humanity?

**Comment by chsamlee** [comment]
In commit [73fa09b](https://github.com/infolab-csail/WikipediaBase/commit/73fa09bf1d2b84cd5fe1134074c5ea7055132ade#diff-cfc342757917786afb58fe5fbafc5685L67), we removed `".* people"` as a classifier regex for people. That is the only regex that matches Plato, so he lost his humanity.

For future reference:
- Instead of adding the regex back, we should modify the `"^\d+ deaths.*"` regex so that it matches string like "340s BC deaths" (Plato) and "11th-century BC deaths" (King Wu of Zhou).
- We should look into expanding the regex list. A possible expansion: we can take a word list of careers and convert them into regexes. There are far too many to do this manually.

**Comment by sfelshin** [comment]
Plato is also a `wikipedia-philosopher`.  Could we figure out from that class that he's a person, or is it too hard because of classes like `wikipedia-musical-artist` where some articles are for people but some are for groups?

**Comment by alvaromorales** [comment]
The code gets hairy when a classifier depends on another classifier (in this case, `PersonClassifier` would depend on `InfoboxClassifier`). We start to run into circular dependency issues.

@chsamlee, thanks for the investigation. `.*people` was too general and lead to false positives. Can you PR a fix for the "deaths" and "births" regexes? It would be great to test the patterns with many examples using 'random articles'. 

I think fixing those regexes (and perhaps adding a couple more) will suffice. If we later notice that PersonClassifier is still inadequate, we can work on an enhancement to look at occupations.
