### ISSUE TITLE
Call WikipediaBase's IMAGE-LIVE script (v.1.2.0)

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#189]
`IMAGE-LIVE` is now implemented natively in WikipediaBase.

Sample usage:

```
(get "wikibase-term" "Tiger" (:code "IMAGE-LIVE" :size 50))
```

**Comment by sfelshin** [comment]
The WikipediaBase 1.2.0 `IMAGE-LIVE` implementation is incompatible with START.  START will not use it, and instead will continue to use the old Omnibase implementation until the implementation can be changed:

START wants to use `IMAGE-LIVE` to convert a specific image file _name_ to a complete image _URL_.  The current implementation of `IMAGE-LIVE` returns a complete image URL for an image file name that _it selects_ for a symbol.

START currently expects to send, e.g.,
```
(get "wikibase-term" "Tigress_at_Jim_Corbett_National_Park.jpg" (:code "IMAGE-LIVE") (:size 400)) 
```
Note that the second argument is an image name rather than a symbol.  This violates the standard calling sequence for `get`, in which the second argument is a symbol.  Alvaro points out that now that we have options, we could change the calling sequence to something like
```
(get "wikibase-term" "Tiger" (:code "IMAGE-LIVE") (:image-file "Tigress_at_Jim_Corbett_National_Park.jpg" :size 400))
```
Sounds good to me.  (START would always supply an image file name, but in the case where the file name was omitted, WikiBase could select an image for the symbol as it does in WikipediaBase 1.2.0.)
