### ISSUE TITLE
wikibase-sections off-by-one error

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#220]
`wikibase-sections` sometimes returns a following section. Example:
```
(get "wikibase-sections" "Boston" (:CODE "Government"))
((:html "<h2><span class=\"mw-headline\" id=\"Parks_and_recreation\">Parks and recreation</span></h2><div class=\"thumb tright\"><div class=\"thumbinner\" style=\"width:222px;\">...<div class=\"thumbcaption\">...
Boston Common seen from the ..."))
```
Note that the attributes are missing a section from the table of contents.  The TOC contains a "Neighborhoods" section after "Cityscapes", but this is missing from the attributes:
```
(get-attributes "wikibase-sections" "Boston")
((:code "History") (:code "Geography") (:code "Cityscapes") (:code "Climate") (:code "Demographics") ...)
```

**Comment by chsamlee** [comment]
The "neighborhood" section is added recently ([May 1 version](https://en.wikipedia.org/w/index.php?title=Boston&oldid=718137153)). Since `get-attributes` uses the markup dump to find out the sections, the attributes may not correspond to the latest HTML version online. Not entirely sure if this is the problem though. @alvaromorales, when was the dump last updated?

Assuming that this is the issue, I can change `get-attributes` to fetch the TOC online instead. It is likely to be slower than the current implementation, but I don't have an estimate of how much slower it will be. (Also, I assume whether the performance hit is acceptable depends on how often START calls `get-attributes`?)

**Comment by alvaromorales** [comment]
The dump was last updated in February or so, this could certainly be the problem. But even if there's an inconsistency between markup in the backend and the live page, we shouldn't return the wrong section. Can we verify that the HTML section heading is the same as the section name we extracted from the markup? Or some other verification step?

START calls `get-attributes` so frequently that wikibase-sections must fetch from the markup. Fetching from the live page would be prohibitively expensive.

**Comment by chsamlee** [comment]
It is possible to verify that HTML sections match with markup sections when `get` is called. What do you think of the following procedure?
1. verify that HTML headings match with markup headings
2. if verification fails, we attempt to fix the section index and obtain the section from HTML
3. if we cannot fix the index (e.g. the section is renamed to a very different title), then obtain the section from markup and use Wikipedia API to render it

**Comment by alvaromorales** [comment]
Sounds like a good plan! This step:

> 1. verify that HTML headings match with markup headings

might be a little more involved. I'm guessing the section heading may contain markup that eventually gets stripped out, so fuzzy matching might be necessary.
