### ISSUE TITLE
Sometimes we get the infobox attribute above the one we were lookign for 

### ISSUE THREAD

**Issue by fakedrake** [infolab-csail/WikipediaBase#35]
@alvaromorales found this one on issue #25 but it's a separate issue. I have *seen* it but when I tried to rerun the tests it was gone. The problem is that the get query asks for the area of the sea and the max width (the previous attribute to the correct one) gets returned.

```
Traceback (most recent call last):
  File "/afs/csail.mit.edu/u/a/alvarom/chris-pywikipediabase/tests/test_resolvers.py", line 108, in test_compat_rx
    self.assertRegexpMatches(ans, rx, msg=msg)
AssertionError:
    Query: '(get "wikipedia-ocean" "Sea of Azov" (:CODE "DEPTH"))'
    Answer: '((:CODE "39,000Â km2 (15,000Â sqÂ mi)1"))'
    Matcher: '7.*met.*23.*ft'
    Completion: 29\38: '7.*met.*23.*ft' not found in u'((:CODE "39,000\xc2\xa0km2 (15,000\xc2\xa0sq\xc2\xa0mi)1"))'
```

**Comment by fakedrake** [comment]
This appeared on travis too but travis now passes and every time I spotted it I then tried

    >>> from wikipediabase.util import get_infobox
    >>> get_infobox('sea of azov').get('area')
    >>> u'39,000\xc2\xa0km2 (15,000\xc2\xa0sq\xc2\xa0mi)[1]'

Which is the correct answer.

**Comment by alvaromorales** [comment]
Note that the Travis build passed because my pull request modified the `.travis.yml` file. Travis recreates the test environment every time you do that (therefore deleting pages.db and renderer.mdb). I believe subsequent builds will fail, since pages.db is not being cleaned up.

Repro steps:
* I pulled the latest version of the code on an Infolab machine, and removed pages.db and renderer.mdb.
* Ran `python setup.py test`, all tests pass.
* Ran `python setup.py test` again. `test_compat_rx (tests.test_resolvers.TestResolvers)` fails on the Sea of Azov.
* Deleted renderer.mdb. test_compat_rx still fails.
* Deleted tests/data/pages.db. All tests pass.

Any ideas why / where in the code this problem is happening? Some context on this bug would be helpful for debugging.

**Comment by fakedrake** [comment]
Travis creates a new clean vm each time it runs AFAIK. Also pages.db and renderer.mdb are not bundled in the git repo (see [data/](https://github.com/fakedrake/WikipediaBase/tree/master/tests/data)).

Good thing you noticed pages.db and not renderer.mdb is the problem though. It thought it was the other way round.
