### ISSUE TITLE
Precision of infobox tree and start_types

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#45]
WikipediaBase uses Wikipedia categories to augment the list of types returned to START.

Some examples:

```python
>>> Infobox('Vladimir Putin').types()
['Template:Infobox officeholder', 'Template:Infobox martial artist']
>>> Infobox('Vladimir Putin').start_types()
['wikipedia-officeholder', 'wikipedia-martial-artist', 'wikipedia-person', 'wikipedia-sportsperson', 'wikipedia-other-sportsperson']


>>> Infobox('Massachusetts Institute of Technology').types()
['Template:Infobox university', 'Template:Infobox US university ranking']
>>> Infobox('Massachusetts Institute of Technology').start_types()
['wikipedia-university', 'wikipedia-us-university-ranking', 'wikipedia-society-and-social-science', 'wikipedia-education']
```

Wikipedia categories don't seem particularly clean, and I'm worried that they might hurt QA precision.

In addition, I don't see how categories are useful as infobox types. If START gets `wikipedia-society-and-social-science` as one of the types of MIT, it will try to look at the attributes of the `society-and-social-science` infobox in the MIT article, which doesn't exist.

Could you explain the motivations for using categories?

**Comment by sfelshin** [comment]
Note that Boris and I would love to be able to access a set of augmented types for a Wikipedia article, but not in the form of fake infoboxes.  We'd want it in the form of language, such as

  'office holder', 'martial artist', 'person', 'sportsperson', 'other sportsperson'

Or for another example, take the East River.  It's infobox is "river".  The first sentence of the article is "The East River is a salt water tidal strait in New York City."  The second sentence starts "The waterway, which is actually not a river despite its name, connects...".  We would be happy to be able to receive something like this:

  'river', 'strait', 'tidal strait', 'salt water tidal strait', 'waterway'

In the case of the East River article, it would take some pretty smart NLP to be able to reliably resolve coreference to determine that "the waterway" means the East River.  A lexical resource like WordNet might be a better way to figure out that a river -- or a strait -- is a waterway.

We've talked to Michael about determining alternative language for article/infobox names, as a follow-on from his current work on determining alternative language for attribute names.  There are many possible sources for the information (infobox name, first sentence, infobox ontology, DBpedia ontology, WordNet, other lexicons), which might be used individually or in combination to contribute to a set of types, I think there's room for several people to contribute.

WikiBase's get-classes command should only return actual infoboxes plus the special classes (as documented at https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/WikipediaBase#SpecialAttributes).  Perhaps WikiBase needs a new command to return types.

Who gets copied on emails to this address?:

  fakedrake/WikipediaBase <reply@reply.github.com>

I don't know how to tell.  I've cc'd Chris, Alvaro, Michael, and Boris explicitly to make sure you all get this email.

-Sue

**Comment by sfelshin** [comment]
> We've talked to Michael about determining alternative language for article/infobox names, as a follow-on from his current work on determining alternative language for attribute names.  There are many possible sources for the information (infobox name, first sentence, infobox ontology, DBpedia ontology, WordNet, other lexicons), which might be used individually or in combination to contribute to a set of types, I think there's room for several people to contribute.

Hopefully DBpedia will have this information — I will keep this in mind as I start using DBpedia’s ontology, but if Python WikipediaBase has another clever way of figuring this out, I would be interested in finding out.

> Who gets copied on emails to this address?:
> 
>   fakedrake/WikipediaBase <reply@reply.github.com>
> 
> I don't know how to tell.  I've cc'd Chris, Alvaro, Michael, and Boris explicitly to make sure you all get this email.

You responded to a GitHub issue, so if you go to the issue’s page on GitHub <https://github.com/fakedrake/WikipediaBase/issues/45> (found in the bottom of the email chain at “view it on GitHub”), you can see the participants in the bottom of the right hand column on that page. Only the people who have responded to the thread (i.e., “participated”, so so far only Sue, Alavro, and now me), or those who are “watching” the repo (Sue, Alvaro, and Chris) get the email, but you can always just CC additional people. So thank you for CCing me, because otherwise I would not have seen this!

Michael

**Comment by fakedrake** [comment]
To address the original question, the answer is that the types returned from start_types() are not intended to correspond to wikipedia symbol. It's information that can be retrieved from wikipedia about the specific infobox. I don't have a strong opinion on what the right behavior should be here. 

I guess this is also a good time to clarify the difference between what wikipediabase considers to be a 'type' and what it considers to be a 'class'.

Python WikipediaBase is currently structured to acomodate logic like the one @sfelshin suggests in the classifiers module (wikipediabase/classifiers.py).

```
>>> kb = KnowledgeBase()
>>> class ConstClassifier(BaseClassifier):
...     def classify(self, symbol):
...         return ['const-class']
...
>>> print kb.classifiers += [ConstClassifier()]
>>> print kb.get_classes("the beatles")
(("wikipedia-term" "wikipedia-musical-artist" "const-class"))
```

(Note that get_classes is memoized so add/removing classifiers in later on will not play very well)

**Comment by alvaromorales** [comment]
> the types returned from start_types() are not intended to correspond to wikipedia symbol.

The 'get-classes' knowledgebase method calls the InfoboxClassifier, which returns both classes and types.

However, the expected behavior of WikipediaBase is to return classes for 'get-classes'.

Should 'types' be moved to a separate 'get-types' knowledgebase method? We could integrate Michael's work into this method. 

From what I understand:

Classes = infobox classes + special WikipediaBase classes
Types = generated definitions, categories, Wordnet synonyms, etc

Perhaps there's a better name for types, but I can't think of one right now :P

**Comment by sfelshin** [comment]
That sounds right to me.  -Sue

**Comment by fakedrake** [comment]
Hmm, here is how I think of it based on my limited knowledge of type theory. A type is a concept that is directly instantiated by the wikipedia symbol. That is the title of the symbol's infobox. I would consider higher order types, as infered from https://en.wikipedia.org/wiki/Wikipedia:List_of_infoboxes, to be types as well.

A class on the other hand is broader, it is more of a label attached to an object, and it is not required to define it. That is, classes may need some sort of heuristic to be determined, and may be relevant in some but not in other contexts.

For example: The Beatles are a band (type) and they could be classified as 20th century musicians.

Following the above logic

types: infobox classes and parent infobox classes
classes: categories, wordnet synonyms, other calculated labels

A special case I find is the generated definitions, ie the logic that Sue proposes. I think that because while from an ontological standpoint it indeed describes the type of an object, from a technical standpoint it is extracted from free text. That is some clever heuristic should be employed.

Again, I am not too attached to the above view. I am onboard with alvaro's suggestion too.

**Comment by sfelshin** [comment]
Apologies if I'm belaboring the obvious.

"Class" and "type" have many different definitions and uses in different fields.  In the context of START/Omnibase/WikiBase, "class" has a very specific meaning, as follows:

When we have a set of objects that are ontologically the same, and that are stored with similar naming schemes in some coherent location (usually on a website, and usually with one webpage per object), the "class" is the name we use for the set.  For example, the IMDb website has information about movies, people, and so forth.  We have two Omnibase classes for the IMDb source, called imdb-movie and imdb-person.  The Infoplease website has several kinds of information, and Omnibase contains several classes for this source: infoplease-country, infoplease-island, infoplease-inventor, etc.  Each class supports a variety of attributes for the objects in the class.  An attribute need not be present/successful for _every_ object in the class -- for example, the imdb-movie class implements a DIRECTOR attribute, but it fails for "Metropolis (1965)" which was such a low-budget indie film that it didn't have a director -- but all attributes should be meaningful for the objects of the class.  Compare how we should answer about a missing/failed attribute _value_:
  Q: Who directed Metropolis (1965)?
  A: Metropolis (1965) doesn't have a director.
with how we should answer about a missing/undefined _attribute_:
  Q: Who directed the Atlantic Ocean?
  A: Oceans don't have directors.  (or perhaps: People don't direct oceans.)

Under this meaning of "class", Wikipedia infoboxes correspond exactly to classes.  The WikiBase "get-classes" command should return the names of all infoboxes (and special fake infoboxes) and nothing else.  We can have any number of other commands to return other things, and even if those things are called classes in other contexts, they shouldn't be called classes in WikiBase.  We shouldn't rename the "get-classes" command in WikiBase, because then we'd also have to change from "class" to some other term in Omnibase and START, and that's too much work.  However, if it seems useful, we can have comments in WikiBase explaining what WikiBase means by "class" and comparing it to other meanings of the word and words for the meaning.

-Sue

**Comment by fakedrake** [comment]
Great. Thank you Sue for clearing up the issue. So to rephrase, wikipediabase should use Infobox classes and what can be inferred from https://en.wikipedia.org/wiki/Wikipedia:List_of_infoboxes and types should be any other inferred labels wikipediabase can/should come up with, right?

**Comment by alvaromorales** [comment]
Ah, subtle detail. 

> what can be inferred from https://en.wikipedia.org/wiki/Wikipedia:List_of_infoboxes

If I understand correctly, this inference step involves looking at the parent infobox classes. For instance, WikipediaBase infers "wikipedia-sportsperson" for Vladimir Putin by looking at the "martial artist" infobox.

However, Putin's article does not have a "sportsperson" infobox -- only a "martial artist" and "officeholder" one.

I think this inferred "class" is actually a "type". WikipediaBase should return classes corresponding to the infoboxes found in the article (and fake infoboxes for WikipediaBase).

**Comment by fakedrake** [comment]
Understood. Also all classes are also types right?

**Comment by alvaromorales** [comment]
Yes. But class:"wikipedia-martial-artist" should be type:"martial artist" (string transformation).

**Comment by sfelshin** [comment]
Thanks for the clarification, Alvaro.  Looks like this thread is converging to the Right Thing.  -Sue

**Comment by michaelsilver** [comment]
So I am building a [database](https://github.com/michaelsilver/wikithingsdb) that should give us paraphrases of Wikipedia symbols. For each article, the DB will include:
**class(es)**: Article's infobox(es)
**synonyms**: [from redirects](https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/WikipediaBase#Get_synonyms_from_redirects)
**type(s)**: definitions from Alvaro's [Whoami](https://github.com/alvaromorales/whoami)
**hypernym(s)**: from the [DBpedia ontology](http://mappings.dbpedia.org/server/ontology/classes/)

Hopefully this will be helpful to WikipediaBase.

@fakedrake @alvaromorales, I have one question: is it kosher to use WikipediaBase's `article.type()` to get infoboxes of articles? Or, is there an easy way to get that directly from the Wikipedia API? (which, if there is, I'm sure that's implemented in Alvaro's PR #47).

**Comment by alvaromorales** [comment]
Wikipedia does not have an API endpoint to get infoboxes. 

I don't think that WikipediaBase should be used for scraping (anything that involves scanning all articles to get a value). Although possible and probably fine, I wouldn't like to push the limits and get us banned from Wikipedia. 

If all you want is to get infoboxes, you should write a simple parser of the XML dump that just looks for a regex that matches something like "{{Infobox officeholder" -- this is how WikipediaBase gets article infoboxes given the article wiki markup.

**Comment by michaelsilver** [comment]
Why would we get banned? The API etiquette is as long as you make request in series (no matter how fast) and not in parallel, you will not be banned. Unless that part of the code uses the real, live, human Wikipedia website (bad, bad, bad), why would it be a problem? -- seems like WikipediaBase does the scraping already

It's another matter if you think it will be dramatically faster to write something of my own (code time+run time). If this is the case, seems like this group of people is pretty experienced with Wiki's XML -- any advice on which of the [dump files](https://dumps.wikimedia.org/enwiki/20150304/) to use and what Python library would be best for scraping it?

**Comment by sfelshin** [comment]
On Aug 6, 2015, at 2:21 PM, Alvaro Morales wrote:
> If all you want is to get infoboxes, you should write a simple parser of the XML dump that just looks for a regex that matches something like "{{Infobox officeholder" -- this is how WikipediaBase gets article infoboxes given the article wiki markup.

How does one recognize things that don't explicitly say "{{Infobox"?  E.g.,

a) The article for "Sium sisarum" has
  {{taxobox

b) The article for "Suspension bridge" has
  {{BridgeTypePix
and I assume that somewhere or other BridgeTypePix expands to an infobox.  Compare "Cable-stayed bridge" which has
  {{Infobox bridge type
I don't know why the two bridge types are so different.

-Sue

**Comment by alvaromorales** [comment]
Scraping is a workload that does not take advantage of caching. The production workload of WikipediaBase is not scraping.

> Unless that part of the code uses the real, live, human Wikipedia website (bad, bad, bad)
I don't get what you mean here. Yes, we query wikipedia.org for articles directly, through /index.php. Faster than the API, and I assumed that the same guidelines apply. We should be able to switch it to use the API quite easily, if we feel that's better (discuss in #47).

> The API etiquette is as long as you make request in series (no matter how fast) and not in parallel, you will not be banned.
Again, I wouldn't want to push the limits here and find out if this is indeed a true claim.

> It's another matter if you think it will be dramatically faster to write something of my own (code time+run time).
It would have a (much) faster run time, but it would take you time to code up. I'm giving my opinion to your question "is it kosher to use WikipediaBase for this task?"

**Comment by michaelsilver** [comment]
Understood. I won't use WikipediaBase. Thanks for your response.
