### ISSUE TITLE
Integrate WikithingsDB into WikipediaBase

### ISSUE THREAD

**Issue by michaelsilver** [infolab-csail/WikipediaBase#66]
WikithingsDB provides a whole bunch of data that could be used by WikipediaBase and START. We need to add prefixes to avoid namespace conflicts, but the general API is:

(get-types “Bill Clinton”)
(get-classes “Bill Clinton”)
(get-hypernyms “Bill Clinton”)
(get-class-hypernyms “wikipedia-president”)
(get-articles-of-type “French mathematician”)
(get-articles-of-class “wikipedia-president”)
(get-hyponyms “company”) ==> airline, bank, brewery, …
(get-synonyms “Bill Clinton”)

Any ideas on "The Right" namespacing?

**EDIT: see my second post that broadens the scope of the discussion of how best to integrate WikithingsDB into WikipediaBase.**

**Comment by alvaromorales** [comment]
How about `wdb`, as in `(get-wdb-types "Bill Clinton")`

**Comment by fakedrake** [comment]
hello! is this issue on the right project? also, at the risk of
[bikeshedding](https://wikipedia.org/wiki/Parkinson%27s_law_of_triviality)
i would say go the commonlisp way of naming things like
`<namespace>-<function name>` ie `wdb-get-types`.

**Comment by michaelsilver** [comment]
I created an issue in WikipediaBase to make sure the whole WikiBase team is on the same page about changes I will be making in *WikipediaBase's* code.

To get explicit about this, the overlap is in get-classes, meant to get an article's infoboxes. One variant would be to use `wdb` as in `get-wdb-classes`. That is indeed trivial and we can end that discussion. 

However, I am wondering about the difference between WikipediaBase's own `get-classes` and WikithingsDB's `get-classes`. How does WikipediaBase get the infoboxes of an article? WikithingsDB just looks at the markup, and currently greps for `'{{[iI]nfobox[/\w\. ]+'`. If they work virtually the same way by looking at the article's markup, what's the point of keeping two separate functions? Here are some possibilities:

1.  If WikiBase and WikithingsDB get the classes in the same way, just get rid of one or the other. I vote for using WikithingsDB to store data like this, since it can also do fancy things such as `(get-articles-of-class “wikipedia-president”)`. It's nice to have one container for all Wikipedia-related data. 

1.  If they work differently, then in the interest of keeping things simple for START, why don't we just have one function `get-classes` and leave it up to WikipediaBase to find the union of its own `get-wikibase-classes` and `get-wdb-classes`. 

1.  Or, even if they work differently, add the "other" datasource to WikithingsDB and just use WikithingsDB to store this data (similar to point 1). 

Then, I am wondering about `get-types` and `get-synonyms`. I remember a discussion a while ago about the difference between types and classes. What happened to WikiBase's types? Should we combine WikithingsDB's types (extracted from article's first sentence) and WikiBase's types, or put them all in WikithingsDB? Same for synonyms. WikithigsDB uses @fakedrake's suggestion of using the redirect MySQL table to get synonyms. How should that be more deeply integrated into WikiBase?

(I see this issue as a place to discuss how WikithingsDB will be integrated into WikipediaBase; I hope that explains why I crated the issue.)

**Comment by alvaromorales** [comment]
Note that @fakedrake is suggesting `wdb-get-classes` instead of `get-wdb-classes`.

Why integrate WikithingsDB into WikipediaBase? WikipediaBase has great infrastructure to provide a lisp API (enchantments, frontend, etc), so there's no need to reinvent the wheel.

WikipediaBase goes to wikipedia.org, gets the latest version of the article, and finds infoboxes. WikithingsDB has data from when the DB was created. We would like to keep WikipediaBase as up-to-date as possible without manually building a database. If a page is updated and a new infobox is added, but WikithingsDB is not rebuilt, the query would fail. We need both `get-classes` functions.

Instead of trying to find unions between functions in WikipediaBase and WikithingsDB, I suggest we keep them under separate namespaces. We haven't thoroughly tested WikithingsDB yet, and we don't know how Omnibase is going to make use of its API.

Regarding synonyms, WikithingsDB should have a script that outputs a synonyms file for Omnibase. I doubt that we need a tighter integration than that. Synonyms are loaded at compile time.

**How should the WikithingsDB knowledge base be implemented?** I believe `KnowledgeBase` can be extended. Should we have a subfolder of 3rd-party knowledge bases that extend `KnowledgeBase`? Should we just add functions to `knowledgebase.py`?
