### ISSUE TITLE
Return :yyyymmdd and :html for wikibase-person

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/WikipediaBase#87]
[Originally raised by @sfelshin over email]

wikipedia-person BIRTH-DATE should be less quick to return :yyyymmdd.

Note that both classes return the same result:

$ telnet nauru 8023
(get "wikipedia-person" "Sarah Bernhardt" (:code "BIRTH-DATE"))
((:yyyymmdd 18441022))

$ telnet nauru 8023
(get "wikibase-person" "Sarah Bernhardt" (:code "BIRTH-DATE"))
((:yyyymmdd 18441022))

But if we look at the Wikipedia article https://en.wikipedia.org/wiki/Sarah_Bernhardt we find

> Sarah Bernhardt (French: [sa.ʁa bɛʁ.nɑʁt];[2] c. 22/23 October 1844 – 26 March 1923) was a French stage and early film actress.

and
  
> Born	Rosine Bernardt
> c. 22 October 1844[1]
> Paris, France

It seems to me that this would be a good opportunity to return something along the lines of

$ telnet nauru 8023
(get "wikipedia-person" "Sarah Bernhardt" (:code "BIRTH-DATE"))
```
((:yyyymmdd 18441022 :html "<tr>
<th scope="row">Born</th>
<td><span class="nickname">Rosine Bernardt</span><br />
c. <span style="display:none">(<span class="bday">1844-10-22</span>)</span>22 October 1844<sup id="cite_ref-1" class="reference"><a href="#cite_note-1"><span>[</span>1<span>]</span></a></sup><br />
<span class="birthplace">Paris, France</span></td>
</tr>"))
```

$ telnet nauru 8023
(get "wikibase-person" "Sarah Bernhardt" (:code "BIRTH-DATE"))
((:yyyymmdd 18441022 :html "c. 22/23 October 1844"))

**Comment by sfelshin** [comment]
See also https://github.com/infolab-csail/WikipediaBase/issues/94. In the case of Beethoven, we may question whether we should return a `:yyyymmdd` date at all, given that there is only a baptismal date and no actual birth date. If someone asks START, "Who was born earlier, Beethoven or Mozart?", it's a bit of a shame if we can't do a mathematical calculation using yyyymmdd values, but we could still fall back on giving the user each composer's non-yyyymmdd answer and letting them figure it out for themself. On the other hand, if someone asks "list composers born between 1750 and 1800", it's quite embarrassing if we leave Beethoven out.

We could explore various possibilities. START could only ask for yyyymmdd values when absolutely necessary for mathematical calculations, so that we'd answer "when was Beethoven born" with "baptised 17 December 1770" but "how many days after Mozart was Beethoven born" with a slightly inaccurate day count. We could add a marker in the value to indicate that the yyyymmdd date is questionable (compare https://github.com/infolab-csail/WikipediaBase/issues/91). Or something else.

**Comment by alvaromorales** [comment]
See follow-up discussions in #107

**Comment by chsamlee** [comment]
We are also returning :yyyymmdd values for date-related infobox queries, such as
```(get "wikipedia-military-conflict" "World War I" (:code "date"))```
Should this behavior be kept? It doesn't seem logical to return a single date in this case.

**Comment by sfelshin** [comment]
I agree that is is illogical to return a single yyyymmdd date for World War I's `(:code "date")`.  I think that as with other dates, WikipediaBase should prefer precision over recall.  If it's pretty confident that there is just one date and it is relevant, it should return a `:yyyymmdd` value (presumably along with an `:html` value as well).  Otherwise, it should only return `:html`.  It should not return an yyyymmdd date when there is only one date but it isn't obviously the value, e.g.:
   * Bennington College (July 14, 1987)
   * before July 14, 1987

This is similar to precision/recall issues for birth and death dates; see https://github.com/infolab-csail/WikipediaBase/issues/94.  WikipediaBase should not return a single date when there are several.
