### ISSUE TITLE
Separate wikibase-person BIRTH-DATE from BIRTH-DATE from infobox

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#92]
@alvaromorales says:

> `wikibase-person`'s `BIRTH-DATE` often comes from the infobox. This functionality is described in the Ruby-WikipediaBase wiki page:

>> `BIRTH-DATE`, `wikibase-person`
>> Fetched from the infobox, or, if it is not found, from the article, or, if it is not found, the category information of the article. Always relies on the first date of birth found, matching one of several supported formats.

> (except for the bit about categories; we're not currently using them for dates)

> Perhaps it would make more sense to change the code and separate these implementations:

>   - `wikipedia-`*class* ==> date from the infobox
>   - `wikibase-person` ==> date from the first sentence of the article

> START would have the choice of which date to ask for. `wikibase-person` should probably be a fallback if the infobox doesn't contain a date attribute.

I would definitely prefer this.

**Comment by alvaromorales** [comment]
This involves deleting logic that uses `InfoboxResolver` and `InfoboxClassifier` in PersonClassifier: https://github.com/infolab-csail/WikipediaBase/blob/master/wikipediabase/resolvers/person.py#L49

To make sure that this change works, we need to find a Wikipedia article where the birth or death date in the first sentence has a slightly different format than the one in the infobox.

**Comment by sfelshin** [comment]
Hey, isn't this implemented?  I don't see why we would need to find a Wikipedia article where the birth or death date in the first sentence has a slightly different format than the one in the infobox.  Under the current design, if we get answers to both of these queries:
```
(get "wikibase-person" <person> (:code "BIRTH-DATE"))
(get "wikipedia-person" <person> (:code "BIRTH-DATE"))
```
isn't this issue necessarily resolved?

**Comment by alvaromorales** [comment]
The goal of this issue is to have a distinction between dates from infoboxes and dates parsed from the first sentence of an article. This separation of functionality will let the caller know where the answer came from. The caller can then decide which answer to pick.

Under the current design, if an infobox contains BIRTH-DATE, these two _different_ queries return the same answer:

```
(get "wikibase-person" <person> (:code "BIRTH-DATE"))
(get "wikipedia-person" <person> (:code "BIRTH-DATE"))
```

We chose to conflate these implementations because we do a better job at parsing dates from infoboxes than from the first sentence. @chsamlee is working on fixing our ability to parse dates from the first sentence (#94). Once that is complete, we can implement this enhancement.

The API will be cleaner if these implementations are separated:

- wikipedia-class ==> date from the infobox
- wikibase-person ==> date from the first sentence of the article
